# -*- coding: utf-8 -*-
"""data cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13emjMzNLaGs9S-PC0Fg-zwZJVYu8x7yD
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('Churn_Modelling (3).csv')

df.info()

df.isnull()

print(df.isnull().sum())

updated_df=df.dropna(axis=1)

updated_df.info()

df['Age'].mean()

df['Age'].median()

updated_df=df
updated_df['Age']=updated_df['Age'].fillna(df['Age'].mean())
updated_df.info()