# -*- coding: utf-8 -*-
"""feature scalingpynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D28SW94s-YvMgf6RiQArBnV4QRRS0J1c
"""

pip install -U scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Churn_Modelling (3).csv')

df.info()

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

df.head()

df.describe().round(2)

new_df=pd.DataFrame(df,columns=['Age','Tenure'])

new_df.isnull().sum()

new_df.head(5)

new_df.tail(5)



new_df['Age']=new_df['Age'].fillna(new_df['Age'].mean())

new_df.info()

